#### Module 4a – Assignment 2
#### Use TensorFlow framework to implement Example 4.2

In [3]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd
import numpy as np


100 +(64 % 50)
# Load the Iris dataset
iris = load_iris()

# Extract the first two classes (setosa and versicolor)
X = iris.data[:100, :]
y = iris.target[:100]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, activation='sigmoid', input_shape=(4,))
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10)

# Make predictions
y_pred = np.argmax(model.predict(X_test), axis=1)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate the confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


C:\Users\DELL_G7\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5125 - loss: 1.2770
Epoch 2/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5359 - loss: 1.1530 
Epoch 3/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5437 - loss: 1.1687 
Epoch 4/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5203 - loss: 1.2181  
Epoch 5/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5359 - loss: 1.1574 
Epoch 6/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5086 - loss: 1.2018 
Epoch 7/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5281 - loss: 1.1506  
Epoch 8/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5437 - loss: 1.0959  
Epoch 9/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5320 - loss: 1.1306 
Epoch 10/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5555 - loss: 1.0880 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step
Accuracy: 0.6
Confusion Matrix:
 [[12  0]
 [ 8  0]]


### Using Breast Cancer dataset
#### Module 4a – Assignment 2
#### Use TensorFlow framework to implement Example 4.2

In [5]:
import tensorflow as tf
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# Load the Breast Cancer dataset
data = load_breast_cancer()

X = data.data
y = data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, activation='sigmoid', input_shape=(X_train.shape[1],))
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10)

# Make predictions

y_pred = np.argmax(model.predict(X_test), axis=1)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate the confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Epoch 1/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.6133 - loss: 265.4900
Epoch 2/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6278 - loss: 248.1059
Epoch 3/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6026 - loss: 243.7588
Epoch 4/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6180 - loss: 223.7396
Epoch 5/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6402 - loss: 200.3396
Epoch 6/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6447 - loss: 174.2408
Epoch 7/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6278 - loss: 174.6900
Epoch 8/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6125 - loss: 166.1091
Epoch 9/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6543 - loss: 125.3271
Epoch 10/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6494 - loss: 118.2753
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Accuracy: 0.37719298245614036
Confusion Matrix:
 [[43  0]
 [71  0]]


### Example 4.2
#### Develop a Python Code with Sklearn framework for classification of the first
#### two species of the Iris Dataset.

In [5]:
#Import required libraries
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd
#Load the Iris dataset
iris = load_iris()
#View the iris data keys
iris.keys()#it is a key of dictionary iris
iris.target_names
##Convert data and target into a data frame.
#Extract the First 100 Features
X = pd.DataFrame(data = iris.data[:100,:], columns = iris.feature_names)
X.head(100) #Inspect the features
#Target
y = pd.DataFrame(data=iris.target[:100], columns = ['irisType'])
y.head(100)
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)# Create a Perceptron classifier
mdlPercept = Perceptron()
# Train the classifier
mdlPercept.fit(X_train, y_train)
# Make predictions on the test set
y_pred = mdlPercept.predict(X_test)
# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
#Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

Accuracy: 1.0
Perceptron Confusion Matrix:
 [[12  0]
 [ 0  8]]


g:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Example 4.2
#### Develop a Python Code with Sklearn framework for classification of the first two species of the Iris Dataset.
#### Using a dataset that is equals to  100 + ( last2digitsofmatricno % 50)

In [9]:
#Import required libraries
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd
#Load the Iris dataset
iris = load_iris()
#View the iris data keys
iris.keys()#it is a key of dictionary iris
iris.target_names
# creating dataset value
last_digits_of_matric = 61
dataCount =100 +(last_digits_of_matric % 50)
print(f"data count is {dataCount}")
##Convert data and target into a data frame.
#Extract the First {dataCount} Features
X = pd.DataFrame(data = iris.data[:dataCount,:], columns = iris.feature_names)
X.head(dataCount) #Inspect the features
#Target
y = pd.DataFrame(data=iris.target[:dataCount], columns = ['irisType'])
y.head(dataCount)
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)# Create a Perceptron classifier
mdlPercept = Perceptron()
# Train the classifier
mdlPercept.fit(X_train, y_train)
# Make predictions on the test set
y_pred = mdlPercept.predict(X_test)
# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
#Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

data count is 111
Accuracy: 0.8695652173913043
Perceptron Confusion Matrix:
 [[10  0  0]
 [ 1  9  2]
 [ 0  0  1]]


g:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Module 4b assignment

#### Develop a classification model using the breast_cancer dataset in SKlearn and the MLP classifier

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load the Breast Cancer dataset
data = load_breast_cancer()
X = data.data
y = data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the MLP Classifier
clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=42)
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.9385964912280702

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.84      0.91        43
           1       0.91      1.00      0.95        71

    accuracy                           0.94       114
   macro avg       0.96      0.92      0.93       114
weighted avg       0.94      0.94      0.94       114



### Module 4b assignment

#### Develop a classification model using the load_wine dataset in SKlearn and the MLP classifier

In [2]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load the Wine dataset
data = load_wine()
X = data.data
y = data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the MLP Classifier
clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=42)
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.9722222222222222

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.93      1.00      0.97        14
           2       1.00      1.00      1.00         8

    accuracy                           0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36



g:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
