### Classwork
### Adenuga Ebunifeoluwa Ayomikun 19cj025761

In [38]:
#Softmax
import math
weightedsum = [1.2,  0.9,  0.75,  0.8,  1.5]
for i in weightedsum:
    output = (math.exp(i))/(math.exp(weightedsum[0]) + math.exp(weightedsum[1]) + math.exp(weightedsum[2]) + math.exp(weightedsum[3]) + math.exp(weightedsum[4]))
    print("output of ",(i)," is ",(output))

output of  1.2  is  0.22734376052507407
output of  0.9  is  0.16842040015527598
output of  0.75  is  0.14496078180634608
output of  0.8  is  0.15239308002108304
output of  1.5  is  0.3068819774922209


In [27]:
#Relu
for i in weightedsum:
    relu_output = (max(0, i)) 
    print("output of ",(i)," is ",relu_output)

output of  1.2  is  1.2
output of  0.9  is  0.9
output of  0.75  is  0.75
output of  0.8  is  0.8
output of  1.5  is  1.5


In [28]:
#Bipolar Sigmoid
for i in weightedsum:
  bipolar_sigmoid_output = ((1 - math.exp(-i)) / (1 + math.exp(-i)))   
  print("output of",(i)," is ",bipolar_sigmoid_output)

output of 1.2  is  0.5370495669980352
output of 0.9  is  0.4218990052500079
output of 0.75  is  0.35835739835078595
output of 0.8  is  0.3799489622552249
output of 1.5  is  0.6351489523872873


In [2]:
# Import required libraries
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

# Load the Iris dataset
iris = load_iris()

# Convert data and target into a data frame.
# Extract the First 100 Features
X = pd.DataFrame(data=iris.data[:135, :], columns=iris.feature_names)
y = pd.DataFrame(data=iris.target[:135], columns=['irisType'])

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Perceptron classifier
mdlPercept = Perceptron()

# Train the classifier
mdlPercept.fit(X_train, y_train)

# Make predictions on the test set
y_pred = mdlPercept.predict(X_test)

# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7407407407407407
Perceptron Confusion Matrix:
 [[13  0  0]
 [ 6  0  1]
 [ 0  0  7]]


C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [6]:
import tensorflow as tf
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

# Load the Digits dataset
digits = load_digits()

# Convert data and target into a data frame.
X = pd.DataFrame(data=digits.data)
y = pd.DataFrame(data=digits.target, columns=['digit'])

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert pandas DataFrames to numpy arrays
X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

# Define a simple perceptron model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='softmax', input_shape=(X_train.shape[1],))
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, verbose=0)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy:", accuracy)

# Make predictions on the test set
y_pred_prob = model.predict(X_test)
y_pred = y_pred_prob.argmax(axis=1)

# Generate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Perceptron Confusion Matrix:\n", conf_matrix)


C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\src\layers\core\dense.py:73: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Accuracy: 0.9694444537162781
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Perceptron Confusion Matrix:
 [[32  0  1  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 32  1  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  1  0  0 45  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  1  0  0 29  0]
 [ 0  0  0  1  0  0  0  0  2 37]]
